version: '3.5'

services:
  postgres:
  container_name: postgres_empresa
  image: postgres
  environment: 
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
    POSTGRES_DB: postgres_empresa
  volume:
    - ./data:/data/postgres
  ports:
    - "80:80"